<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>CSBG Annual Report — {{ $agency['entity_name'] }}</title>
    <style>
        body { font-family: sans-serif; font-size: 10px; color: #333; margin: 0; padding: 20px; }
        h1 { font-size: 16px; margin-bottom: 5px; }
        h2 { font-size: 13px; margin: 15px 0 8px; border-bottom: 1px solid #999; padding-bottom: 3px; }
        h3 { font-size: 11px; margin: 10px 0 5px; color: #555; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 10px; }
        th, td { border: 1px solid #ccc; padding: 3px 5px; text-align: left; }
        th { background: #f0f0f0; font-size: 9px; text-transform: uppercase; }
        td.num { text-align: right; }
        .header { margin-bottom: 15px; }
        .header p { margin: 2px 0; font-size: 10px; color: #666; }
        .footer { position: fixed; bottom: 10px; left: 20px; right: 20px; font-size: 8px; color: #999; border-top: 1px solid #eee; padding-top: 3px; }
        .page-break { page-break-after: always; }
    </style>
</head>
<body>
    <div class="header">
        <h1>CSBG Annual Report V2.1</h1>
        <p><strong>{{ $agency['entity_name'] }}</strong> — {{ $agency['state'] }}</p>
        <p>UEI: {{ $agency['uei'] ?: 'N/A' }} &middot; Reporting Period: {{ $agency['reporting_period'] }} &middot; FFY {{ $fiscalYear }}</p>
    </div>

    @yield('content')

    <div class="footer">
        Generated by CAPIntake on {{ now()->format('M j, Y g:i A') }} &middot; Page <span class="pagenum"></span>
    </div>
</body>
</html>
