<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>NPI Report</title>
    <style>
        body {
            font-family: Arial, Helvetica, sans-serif;
            font-size: 10px;
            color: #1a1a1a;
            margin: 0;
            padding: 20px;
        }

        .header {
            text-align: center;
            margin-bottom: 20px;
            border-bottom: 2px solid #1a1a1a;
            padding-bottom: 10px;
        }

        .header h1 {
            font-size: 16px;
            margin: 0 0 4px;
        }

        .header p {
            font-size: 11px;
            margin: 2px 0;
            color: #555;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }

        th {
            background-color: #2d3748;
            color: white;
            text-align: left;
            padding: 6px 8px;
            font-size: 9px;
            text-transform: uppercase;
            letter-spacing: 0.5px;
        }

        th.num {
            text-align: right;
        }

        td {
            padding: 5px 8px;
            border-bottom: 1px solid #e2e8f0;
        }

        td.num {
            text-align: right;
            font-variant-numeric: tabular-nums;
        }

        tr.goal-row {
            background-color: #edf2f7;
            font-weight: bold;
        }

        tr.goal-row td {
            padding: 8px;
            border-bottom: 2px solid #cbd5e0;
            font-size: 11px;
        }

        tr.indicator-row td {
            padding-left: 20px;
        }

        tr.grand-total {
            background-color: #2d3748;
            color: white;
            font-weight: bold;
        }

        tr.grand-total td {
            padding: 8px;
            border: none;
            font-size: 11px;
        }

        .footer {
            margin-top: 30px;
            font-size: 8px;
            color: #999;
            text-align: center;
            border-top: 1px solid #e2e8f0;
            padding-top: 10px;
        }

        .zero {
            color: #a0aec0;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>CSBG National Performance Indicators Report</h1>
        <p><strong>Reporting Period:</strong> {{ $startDate }} &ndash; {{ $endDate }}</p>
        <p><strong>Generated:</strong> {{ now()->format('m/d/Y h:i A') }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th style="width: 60px;">NPI Code</th>
                <th>Goal / Indicator</th>
                <th class="num" style="width: 100px;">Unduplicated<br>Individuals</th>
                <th class="num" style="width: 80px;">Total<br>Services</th>
                <th class="num" style="width: 80px;">Total<br>Value ($)</th>
            </tr>
        </thead>
        <tbody>
            @foreach($report as $goal)
                <tr class="goal-row">
                    <td>Goal {{ $goal['goal_number'] }}</td>
                    <td>{{ $goal['goal_name'] }}</td>
                    <td class="num">{{ number_format($goal['goal_total_clients']) }}</td>
                    <td class="num"></td>
                    <td class="num"></td>
                </tr>
                @foreach($goal['indicators'] as $indicator)
                    <tr class="indicator-row">
                        <td>{{ $indicator['indicator_code'] }}</td>
                        <td>{{ $indicator['indicator_name'] }}</td>
                        <td class="num {{ $indicator['unduplicated_clients'] === 0 ? 'zero' : '' }}">
                            {{ number_format($indicator['unduplicated_clients']) }}
                        </td>
                        <td class="num {{ $indicator['total_services'] === 0 ? 'zero' : '' }}">
                            {{ number_format($indicator['total_services']) }}
                        </td>
                        <td class="num {{ $indicator['total_value'] == 0 ? 'zero' : '' }}">
                            ${{ number_format($indicator['total_value'], 2) }}
                        </td>
                    </tr>
                @endforeach
            @endforeach
            <tr class="grand-total">
                <td></td>
                <td>GRAND TOTAL (Unduplicated Across All Goals)</td>
                <td class="num">{{ number_format($grandTotal) }}</td>
                <td class="num"></td>
                <td class="num"></td>
            </tr>
        </tbody>
    </table>

    <div class="footer">
        Generated by CAPIntake &mdash; {{ config('app.name') }} &mdash; {{ now()->format('m/d/Y h:i A') }}
    </div>
</body>
</html>
